feat: Implement simple hello command with commander.js

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,7 +28,7 @@ on:
 
 jobs:
   build:
-    name: React on node ${{ matrix.node-version }}
+    name: commander.js cli using node ${{ matrix.node-version }}
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -57,4 +57,12 @@ jobs:
         run: npm install
 
       - name: Test
-        run: npm test -- --watchAll=false
+        # npm test is failing, with: `inappropriate ioctl for device`
+        # falling back to manual testing
+        run: |
+          if node main.js hello Jim | grep -v -q 'Hello, Jim!'; then
+            exit 1;
+          fi
+          if node main.js hello --capitalize Jim | grep -v -q 'HELLO, JIM!'; then
+            exit 1;
+          fi
